# CAUTION:
#   Not all features of a generic GitHub action is supported: https://github.com/actions/runner/issues/646
#
# **What does Composite Run Steps Not Support**
#
# We don't support setting conditionals, continue-on-error, timeout-minutes, "uses", and secrets on individual steps within a composite action right now.
#
# (Note: we do support these attributes being set in workflows for a step that uses a composite run steps action)
#

name: accum-board-stats
description: 'GitHub composite action to request and accumulate a forum board post replies and views statistic'

inputs:
  board_name:
    description: 'Board name'
    required: true
    # examples:
    # - totalcmd
    # - doublecmd

  topic_query_url:
    description: 'URL to query topic or post to request its replies and views'
    required: true
    # example:
    #   https://myboard.com/board/search.php?keywords="{{SearchPhrase}}"&terms=all&author={{TopicAuthor}}&fid%5B%5D={{ForumId}}&sc=0&sf=titleonly&sr=topics&sk=i&sd=d&st=0&ch=1&t=0&submit=Search

  replies_sed_regexp:
    description: 'Sed regexp to match the replies value'
    required: true
    # example:
    #   `s/.*class="posts"[^0-9]*([0-9.]+).*/\1/p`

  views_sed_regexp:
    description: 'Sed regexp to match the views value'
    required: true
    # example:
    #   `s/.*class="views"[^0-9]*([0-9.]+).*/\1/p`

  curl_flags:
    description: 'additional curl flags'
    # example:
    #   `-H 'Cache-Control: no-cache'`

  deps_repo_owner:
    description: 'Owner of a repository used to checkout dependencies'
    required: true

  deps_repo_branch:
    description: 'Repository branch used to checkout dependencies'
    default: master

  deps_repo_read_token:
    description: 'PAT token to a repository used to checkout dependencies'
    default: ${{ github.token }}

  stat_entity_path:
    description: 'Statistic entity path to request'
    required: true
    # examples:
    # - traffic/board/totalcmd
    # - traffic/board/doublecmd

  output_repo_owner:
    description: 'Owner of a repository used to output the statistic'
    required: true

  output_repo:
    description: 'Repository name used to output the statistic'
    required: true

  output_repo_branch:
    description: 'Repository branch used to output the statistic'
    default: master

  output_repo_dir:
    description: 'Output repository relative directory path to store requested and accumulated statistic'
    required: true
    # examples:
    # - traffic/board/totalcmd
    # - traffic/board/doublecmd

  output_repo_write_token:
    description: 'PAT token to the output repository with write/push access rights'
    required: true

# NOTE:
#   Several features below is not supported in a composite action runnner:
#     * conditionals
#     * continue-on-error
#

runs:
  using: "composite"
  steps:
    # step is required to workaround variable expansion in variables
    - name: declare dependent variables
      shell: bash
      run: |
        echo "GH_WORKFLOW_ROOT=$GITHUB_WORKSPACE/gh-workflow" >> $GITHUB_ENV
        echo "stats_dir=$GITHUB_WORKSPACE/board-stats/${{ inputs.output_repo_dir }}" >> $GITHUB_ENV
        echo "stats_json=$GITHUB_WORKSPACE/board-stats/${{ inputs.output_repo_dir }}/latest.json" >> $GITHUB_ENV
        echo "board_name=${{ inputs.board_name }}" >> $GITHUB_ENV
        echo "topic_query_url=${{ inputs.topic_query_url }}" >> $GITHUB_ENV
        echo "replies_sed_regexp=${{ inputs.replies_sed_regexp }}" >> $GITHUB_ENV
        echo "views_sed_regexp=${{ inputs.views_sed_regexp }}" >> $GITHUB_ENV
        echo "curl_flags=${{ inputs.curl_flags }}" >> $GITHUB_ENV

    - name: allocate directories
      shell: bash
      run: |
        mkdir -p $GH_WORKFLOW_ROOT $GITHUB_WORKSPACE/board-stats/${{ inputs.output_repo_dir }}
        echo "WORKFLOW_TEMPDIR=$(mktemp -d)" >> $GITHUB_ENV

    - name: checkout gh-workflow@${{ inputs.deps_repo_branch }}
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.deps_repo_owner }}/gh-workflow
        ref:        ${{ inputs.deps_repo_branch }}
        path:       gh-workflow
        token:      ${{ inputs.deps_repo_read_token }}

    - name: head annotations
      shell: bash
      run: |
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/print-notice.sh
        $GH_WORKFLOW_ROOT/bash/github/print-notice.sh \
          "output repo dir: https://github.com/${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}/tree/${{ inputs.output_repo_branch }}/${{ inputs.output_repo_dir }}"

    - name: checkout board-stats@${{ inputs.output_repo_branch }}
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        ref:        ${{ inputs.output_repo_branch }}
        path:       board-stats
        token:      ${{ inputs.output_repo_write_token }}

    - name: accumulate ${{ inputs.stat_entity_path }}
      id: accum-stats
      shell: bash
      run: |
        chmod ug+x $GH_WORKFLOW_ROOT/bash/board/accum-stats.sh
        $GH_WORKFLOW_ROOT/bash/board/accum-stats.sh
        # caution: no operation after that line if non zero exit code happens above

    - name: commit board-stats
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/board-stats
        git add .
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git commit -m "Automated update: ${{ inputs.stat_entity_path }}$COMMIT_MESSAGE_SUFFIX"

    - name: push board-stats
      uses: ad-m/github-push-action@master
      with:
        repository:   ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        branch:       ${{ inputs.output_repo_branch }}
        directory:    board-stats
        github_token: ${{ inputs.output_repo_write_token }}
